# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='link/document')),
                ('description', models.CharField(max_length=256)),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'verbose_name': 'Document',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FruitCake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('deleted_version', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fruit Cakes',
                'verbose_name': 'Fruit Cake',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='LemonCake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lemon Cakes',
                'verbose_name': 'Lemon Cake',
                'ordering': ('description',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='fruitcake',
            unique_together=set([('number', 'deleted_version')]),
        ),
    ]
